//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApprovalFlow_UpdEntities : DbContext
    {
        public ApprovalFlow_UpdEntities()
            : base("name=ApprovalFlow_UpdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Approve> Approves { get; set; }
        public virtual DbSet<ApproveHistory> ApproveHistories { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<ResponsibilityCodeHierarchy> ResponsibilityCodeHierarchies { get; set; }
        public virtual DbSet<SecurityContact> SecurityContacts { get; set; }
        public virtual DbSet<SecurityContactResponsibilityCode> SecurityContactResponsibilityCodes { get; set; }
    }
}
