//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POCO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityContactResponsibilityCode
    {
        public int SecurityContactResponsibilityCodeId { get; set; }
        public int SecurityContactId { get; set; }
        public int HierarchyId { get; set; }
    
        public virtual ResponsibilityCodeHierarchy ResponsibilityCodeHierarchy { get; set; }
        public virtual SecurityContact SecurityContact { get; set; }
    }
}
